config/routes.rb
Rails.application.routes.draw do

  get 'universes/index'
  root 'universes#index'

  resources :universes do
    resources :heros
  end

  resources :universes do
    resources :demi_gods
  end

  resources :universes do
    resources :gods
  end

  resources :universes do
    resources :myths
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  before_action :set_universe, only: [:show, :edit, :update, :destroy]

  # GET /universes
  # GET /universes.json
  def index
    @universes = Universe.all
  end

  # GET /universes/1
  # GET /universes/1.json
  def show
  end

  # GET /universes/new
  def new
    @universe = Universe.new
  end

  # GET /universes/1/edit
  def edit
  end

  # POST /universes
  # POST /universes.json
  def create
    @universe = Universe.new(universe_params)

    respond_to do |format|
      if @universe.save
        format.html { redirect_to @universe, notice: 'Universe was successfully created.' }
        format.json { render :show, status: :created, location: @universe }
      else
        format.html { render :new }
        format.json { render json: @universe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universes/1
  # PATCH/PUT /universes/1.json
  def update
    respond_to do |format|
      if @universe.update(universe_params)
        format.html { redirect_to @universe, notice: 'Universe was successfully updated.' }
        format.json { render :show, status: :ok, location: @universe }
      else
        format.html { render :edit }
        format.json { render json: @universe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universes/1
  # DELETE /universes/1.json
  def destroy
    @universe.destroy
    respond_to do |format|
      format.html { redirect_to universes_url, notice: 'Universe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_universe
      @universe = Universe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def universe_params
      params.require(:universe).permit(:title, :author, :description)
    end
end

app/helpers/universes_helper.rb
module UniversesHelper
end

app/views/universes/_form.html.erb
<%= form_for(universe) do |f| %>
<% if universe.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(universe.errors.count, "error") %>
        prohibited this universe from being saved:</h2>

    <ul>
        <% universe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="container">
    <div class="card">

        <div class="card-content">

            <div class="card__form">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'card__form-string' %>
            </div>

            <div class="card__form">
                <%= f.label :author %>
                <%= f.text_field :author, class: 'card__form-string' %>
            </div>

            <div class="card__form">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'card__form-text' %>
            </div>

            <div class="button-box">
                <%= f.submit class:'new-link' %>
                <div class="new-link">
                    <%= link_to 'Back', universes_path %>
                </div>
            </div>

        </div>

    </div>
</div>

<% end %>

app/views/universes/edit.html.erb
<section class="universe-hero">
  <h1 class="title-right">Editing Universe</h1>
</section>

<%= render 'form', universe: @universe %>

app/views/universes/index.html.erb
<div class="hero">
  <div class="container">
      <div class="hero-box">
        <div class="hero__title">MYTHOS</div>
        <div class="hero__tag">Create Your Own Universe</div>
      </div>
  </div>
</div>

<section class="about">
  <div class="container">
    <div class="about-content">
      <h1 class="about-content__title">What is Mythos?</h1>
      <div class="about-content__description">Mythos is an open source application where anyone can create their own mythology.  If you want to build a pantheon similar to the Greeks or Vikings, do it. Or build something completely different. Once you create your Universe add individual Myths with Gods, Demi-Gods, and Heroes.  If you want you can also add Myths to other Universes.  So keep an open mind and have fun.</div>
      <div class="button-box">
        <div class="new-link">
          <%= link_to 'Build a New Universe', new_universe_path %>
        </div>
      </div>

    </div>
  </div>
</section>

<section class="main">

    <h1 class="title">Read, Create, or Add to Universes</h1>
    <!-- <div class="title">Check out the Universes Below</div> -->

</section>

    <div class="container">

      <p id="notice"><%= notice %></p>
      <% @universes.each do |universe| %>

      <div class="card">

        <div class="card-content">
          <div class="card-content__title"><%= universe.title %></div>
          <div class="card-content__item">Created By: <%= universe.author %></div>
          <div class="card-content__text"><%= universe.description %></div>

          <div class="button-box">
              <div class="new-link">
                <div><%= link_to 'More Detail', universe %></div>
              </div>
              <div class="new-link">
                <div><%= link_to 'Edit', edit_universe_path(universe) %></div>
              </div>
              <!-- <div class="new-link">
                <div><%= link_to 'Destroy', universe, method: :delete, data: { confirm: 'Are you sure?' } %></div>
              </div> -->
          </div>
        </div>

      </div>
      <% end %>
    </div>

app/views/universes/new.html.erb
<section class="universe-hero">
  <h1 class="title-right">Create a New Universe</h1>
</section>

<%= render 'form', universe: @universe %>

app/views/universes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="card">
        <div class="card-content">
            <div class="card-content__title">
              <%= @universe.title %>
            </div>

            <div class="card-content__item">Author:
              <%= @universe.author %>
            </div>

            <div class="card-content__text">
              <%= @universe.description %>
            </div>

            <div class="button-box">
                <div class="new-link"><%= link_to 'Edit', edit_universe_path(@universe) %></div>
                <!-- <div class="new-link"><%= link_to 'Destroy', @universe, method: :delete, data: { confirm: 'Are you sure?' } %></div> -->
                <div class="new-link"><%= link_to 'Myths', universe_myths_path(@universe, @myths) %></div>
                <div class="new-link"><%= link_to 'Gods', universe_gods_path(@universe, @gods) %></div>
                <div class="new-link"><%= link_to 'Demi-Gods', universe_demi_gods_path(@universe, @demi_gods) %></div>
                <div class="new-link"><%= link_to 'Heroes', universe_heros_path(@universe, @heros) %></div>
                <div class="new-link"><%= link_to 'Back', universes_path %></div>

            </div>
        </div>
    </div>
</div>